name: Build Wheels
on: [push]

jobs:
  linux-x86_64-cp311:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    env:
      DRO_PIP: /opt/python/cp311-cp311/bin/pip
      DRO_OUTPUT: wheelhouse/
    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-cp311-wheel
          path: wheelhouse/*.whl
          if-no-files-found: error
          overwrite: true

