name: Build Wheels
on: [push]

env:
  PLAT: manylinux2014_x86_64
  TAG: 2024-02-08-a1b4ddc

jobs:
  source-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: source-distribution
          path: ${{ github.workspace }}/dist/*.tar.gz
          if-no-files-found: error
          overwrite: true
          compression-level: 0
  linux-x86_64:
    name: linux-x86_64-${{ matrix.abi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [cp310-cp310, cp312-cp312, cp37-cp37m, cp39-cp39, pp37-pypy37_pp73, pp39-pypy39_pp73, cp311-cp311, cp36-cp36m, cp38-cp38, pp310-pypy310_pp73, pp38-pypy38_pp73]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/${{ env.PLAT }}:${{ env.TAG }}
          options: -v ${{ github.workspace }}:/artifacts -v ${{ github.workspace }}:/work -e DRO_PIP=/opt/python/${{ matrix.abi }}/bin/pip -e DRO_SINGLE=1 -e PLAT=${{ env.PLAT }}
          run: /work/build-manylinux.sh
      - name: List Artifacts
        run: ls -la --color=always ${{ github.workspace }}/*.${{ env.PLAT }}.whl
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-${{ matrix.abi }}-wheel
          path: ${{ github.workspace }}/*.${{ env.PLAT }}.whl
          if-no-files-found: error
          overwrite: true
  windows-macos-x64:
    name: ${{ matrix.os }}-x86_64-python${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, macos]
        pyver: ['3.12', '3.11', '3.10', '3.9', '3.8', '3.7', '3.6']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
      - run: pip install build
      - run: python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x86_64-python${{ matrix.pyver }}-wheel
          path: ${{ github.workspace }}/dist/*.whl
          if-no-files-found: error
          overwrite: true
