name: Build Wheels
on: [push]

env:
  PLAT: manylinux2014_x86_64
  TAG: 2024-02-08-a1b4ddc

jobs:
  linux-x86_64:
    name: linux-x86_64-${{ matrix.abi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [cp311-cp311]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/${{ env.PLAT }}:${{ env.TAG }}
          options: -v artifacts:/artifacts -v ${{ github.workspace }}:/work -e DRO_PIP=/opt/python/${{ matrix.abi }}/bin/pip -e DRO_SINGLE=1 -e PLAT=${{ env.PLAT }}
          run: /work/build-manylinux.sh
      - name: List Artifacts
        run: ls -la --color=always artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-${{ matrix.abi }}-wheel
          path: artifacts/*.whl
          if-no-files-found: error
          overwrite: true

