name: Build Wheels
on: [push]

jobs:
  linux-x86_64-cp311:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    env:
      DRO_PIP: /opt/python/cp311-cp311/bin/pip
      DRO_SINGLE: 1
    steps:
      - name: Clone Repository
        run: git clone --recursive --depth 1 --branch master https://github.com/PucklaJ/dynareadout_python.git repo
      - run: cd repo && ./build-manylinux.sh
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-cp311-wheel
          path: /artifacts/*.whl
          if-no-files-found: error
          overwrite: true

